### ISSUE TITLE
Error when preview any document

### ISSUE THREAD

**Issue by ehermontesinos** [HugoHasenbein/redmine_more_previews#35]
I have tried to install and configure the plugin "more_previews" in my redmine environment which has the following configuration and plugins: 

![Screenshot_50](https://user-images.githubusercontent.com/72438735/139837795-1661f0e1-5c7a-4a44-87a8-6c4a2425d154.jpg)

The installation process is simple, since I have installed both libreoffice and pandoc on the server, which is a requirement that the plugin needs to work. It has been installed correctly, and has been configured as needed.

When testing it, making a preview of any file (ods, odt ...) opens an iframe with the document you want to preview but without seeing anything. The production.log file has the following output: 

`Saving attachment '/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/files/2021/10/211027100952_emoji2.png' (7491 bytes)
pdf: Image: error: RBPDF error: No RMagick: Alpha channel not supported: /var/www/educacion/cau_ce/servicioinformatica/redmine_pre/files/2021/10/211027100952_emoji2.png
An error occured while generating preview for /var/www/educacion/cau_ce/servicioinformatica/redmine_pre/files/2021/10/211026181557_3925719f44bd9fd8c186f65606745040.odt
Exception was: undefined method `children' for Dir:Class
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:216:in `copy_over'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:199:in `block in cached_preview'
/usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:195:in `cached_preview'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:162:in `block in preview'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:127:in `synchronize'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:127:in `sync'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:162:in `preview'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:341:in `convert'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachment_patch.rb:40:in `more_preview'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:95:in `send_more_preview'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:66:in `block (2 levels) in more_preview'
/usr/local/rvm/gems/ruby-2.3.8/gems/actionpack-5.2.4.1/lib/action_controller/metal/mime_responds.rb:203:in `respond_to'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:62:in `more_preview'
/usr/local/rvm/gems/ruby-2.3.8/gems/actionpack-5.2.4.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/local/rvm/gems/ruby-2.3.8/gems/actionpack-5.2.4.1/lib/abstract_controller/base.rb:194:in `process_action'
/usr/local/rvm/gems/ruby-2.3.8/gems/actionpack-5.2.4.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.3.8/gems/actionpack-5.2.4.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/rvm/gems/ruby-2.3.8/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/var/www/educacion/cau_ce/servicioinformatica/redmine_pre/lib/redmine/sudo_mode.rb:65:in `sudo_mode'
/usr/local/rvm/gems/ruby-2.3.8/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-2.3.8/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.3.8/gems/actionpack-5.2.4.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/rvm/gems/ruby-2.3.8/gems/actionpack-5.2.4.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/rv…
pdf: Image: error: RBPDF error: No RMagick: Alpha channel not supported:  esto es lo primero que veo
`

**Comment by HugoHasenbein** [comment]
Dear User,

try to

gem install rmagick
it is needed by redmine as well.

Best regards

Stephan
