### ISSUE TITLE
Cliff and Zippy throwing exception "uninitialized constant Cliff::RmpText" and "uninitialized constant Zippy::RmpText"

### ISSUE THREAD

**Issue by jcatrysse** [HugoHasenbein/redmine_more_previews#38]
When trying to preview ZIP files and EML messages, the system throws an identical exception.

Could this be looked after? Or if someone could point me in the direction to search? I looked at the code, but I cannot find something that is obviously wrong.

I am on a FreeBSD system (13.0) and I had some issues with LibreOffice being installed in a non-standard folder (/usr/local/...).

I tried with all the other plugins removed.

Redmine info (all ticked green):
```
Redmine 4.2.3.stable
Standaard beheerderaccount gewijzigd 	
Bestandsrepository schrijfbaar 	
Plugin assets map schrijfbaar (./public/plugin_assets) 	
MiniMagick beschikbaar (optioneel) 	
ImageMagick comversie beschikbaar (optioneel) 	
ImageMagick PDF support available (optional) 	
Libre Office available 	
Pandoc available 	

Environment:
  Redmine version                4.2.3.stable
  Ruby version                   2.7.4-p191 (2021-07-07) [amd64-freebsd13]
  Rails version                  5.2.6
  Environment                    test
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::InlineAdapter
  Mailer delivery                sendmail
```

Thank you.

Exceptions:
```
uninitialized constant Cliff::RmpText
/usr/local/www/redmine/plugins/redmine_more_previews/converters/cliff/lib/cliff.rb:62:in `eml'
/usr/local/www/redmine/plugins/redmine_more_previews/converters/cliff/lib/cliff.rb:46:in `convert'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:179:in `block in transient_preview'
/usr/local/lib/ruby/2.7/tmpdir.rb:89:in `mktmpdir'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:176:in `transient_preview'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:159:in `block in preview'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:127:in `synchronize'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:127:in `sync'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:159:in `preview'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:341:in `convert'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachment_patch.rb:40:in `more_preview'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:101:in `send_more_preview'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:63:in `block (2 levels) in more_preview'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/mime_responds.rb:203:in `respond_to'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:62:in `more_preview'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/abstract_controller/base.rb:194:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/usr/local/www/redmine/lib/redmine/sudo_mode.rb:61:in `sudo_mode'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/activerecord-5.2.6/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/abstract_controller/base.rb:134:in `process'
/usr/local/lib/ruby/gems/2.7/gems/actionview-5.2.6/lib/action_view/rendering.rb:32:in `process'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal.rb:191:in `dispatch'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal.rb:252:in `dispatch'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `each'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `serve'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:840:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/lib/ruby/gems/2.7/gems/railties-5.2.6/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/lib/ruby/gems/2.7/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `block in call'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/local/lib/ruby/gems/2.7/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/lib/ruby/gems/2.7/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'
/usr/local/lib/ruby/gems/2.7/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'
/usr/local/lib/ruby/gems/2.7/gems/passenger/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/local/lib/ruby/gems/2.7/gems/passenger/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/local/lib/ruby/gems/2.7/gems/passenger/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/local/lib/ruby/gems/2.7/gems/passenger/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/local/lib/ruby/gems/2.7/gems/passenger/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

```
An error occured while generating preview for /usr/local/www/redmine/files/2022/02/220202172452_redmine_reporter-151021-m.zip
Exception was: uninitialized constant Zippy::RmpText
/usr/local/www/redmine/plugins/redmine_more_previews/converters/zippy/lib/zippy.rb:193:in `block in ziplist'
/usr/local/www/redmine/plugins/redmine_more_previews/converters/zippy/lib/zippy.rb:185:in `each'
/usr/local/www/redmine/plugins/redmine_more_previews/converters/zippy/lib/zippy.rb:185:in `ziplist'
/usr/local/www/redmine/plugins/redmine_more_previews/converters/zippy/lib/zippy.rb:171:in `ziptoc'
/usr/local/www/redmine/plugins/redmine_more_previews/converters/zippy/lib/zippy.rb:153:in `block in ziptable'
/usr/local/lib/ruby/gems/2.7/gems/rubyzip-2.3.2/lib/zip/file.rb:125:in `open'
/usr/local/www/redmine/plugins/redmine_more_previews/converters/zippy/lib/zippy.rb:152:in `ziptable'
/usr/local/www/redmine/plugins/redmine_more_previews/converters/zippy/lib/zippy.rb:51:in `convert'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:179:in `block in transient_preview'
/usr/local/lib/ruby/2.7/tmpdir.rb:89:in `mktmpdir'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:176:in `transient_preview'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:159:in `block in preview'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:127:in `synchronize'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:127:in `sync'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/conversion.rb:159:in `preview'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/lib/converter.rb:341:in `convert'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachment_patch.rb:40:in `more_preview'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:101:in `send_more_preview'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:63:in `block (2 levels) in more_preview'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/mime_responds.rb:203:in `respond_to'
/usr/local/www/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:62:in `more_preview'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/abstract_controller/base.rb:194:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/usr/local/www/redmine/lib/redmine/sudo_mode.rb:61:in `sudo_mode'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/activerecord-5.2.6/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/abstract_controller/base.rb:134:in `process'
/usr/local/lib/ruby/gems/2.7/gems/actionview-5.2.6/lib/action_view/rendering.rb:32:in `process'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal.rb:191:in `dispatch'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_controller/metal.rb:252:in `dispatch'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `each'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `serve'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:840:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/lib/ruby/gems/2.7/gems/railties-5.2.6/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/lib/ruby/gems/2.7/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `block in call'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/local/lib/ruby/gems/2.7/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/lib/ruby/gems/2.7/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-5.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/lib/ruby/gems/2.7/gems/actionpack-5.2.6/lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/usr/local/lib/ruby/gems/2.7/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'
/usr/local/lib/ruby/gems/2.7/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'
/usr/local/lib/ruby/gems/2.7/gems/passenger/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/local/lib/ruby/gems/2.7/gems/passenger/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/local/lib/ruby/gems/2.7/gems/passenger/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/local/lib/ruby/gems/2.7/gems/passenger/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/local/lib/ruby/gems/2.7/gems/passenger/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by jcatrysse** [comment]
This still throws some exceptions on the zippy converter: 
```
Exception was: undefined method `to_html' for #<Array:0x00000008111b80f0>
Did you mean?  to_xml
               to_yaml
/usr/local/www/redmine/plugins/redmine_more_previews/converters/zippy/lib/zippy.rb:173:in `ziptoc'
```

I was able to resolve this by adding `require 'array'` to `./converters/zippy/lib/zippy.rb` on line 26

**Comment by HugoHasenbein** [comment]
it seems, Rails fails silently during startup and therefore, fails to load libraries and classes. Did you do

bundle install

so that gems are loaded?

**Comment by jcatrysse** [comment]
Hello Dr.

Thank you for helping out!

Yes, I did a `bundle install` in the Redmine root folder, and a `bundle update`, just to be sure.

I was able to resolve the issue by adding the lines I mentioned before, but I am not much of a programmer. So it is more of a trial and error fix...

For the moment, I am stuck with another issue:
```
An error occured while generating preview for /usr/local/www/redmine/files/2022/02/220202172452_redmine_reporter-151021-m.zip
Exception was: undefined local variable or method `assetpath' for #<Zippy:0x000000080f37fd40>
Did you mean?  asset_path
               assetext
               assetext=
               @assetext
/usr/local/www/redmine/plugins/redmine_more_previews/converters/zippy/lib/zippy.rb:219:in `zipcontent'
```

But as I mentioned, I don't really understand all what I am doing.

**Comment by jcatrysse** [comment]
And this one also.

It seems I must have a root cause somewhere... but I can't find it.

```
An error occured while generating preview for /usr/local/www/redmine/files/2022/02/220202173000_sample2.html
Exception was: undefined method `identifier_param' for #<Attachment:0x000000081505fc68>
/usr/local/lib/ruby/gems/2.7/gems/activemodel-5.2.6/lib/active_model/attribute_methods.rb:430:in `method_missing'
/usr/local/www/redmine/plugins/redmine_more_previews/converters/mark/lib/mark.rb:72:in `pandoc'
/usr/local/www/redmine/plugins/redmine_more_previews/converters/mark/lib/mark.rb:55:in `convert'
```

**Comment by HugoHasenbein** [comment]
usually this happens, when rails silently fails during the course of starting up. Then the status is somewhat undefined. Rails responds to server requests but misses all definitions after the failure.

**Comment by jcatrysse** [comment]
Sorry to bother on this, but is there a way to find out if this is the case, and what is happening in detail?

All my other functions in Redmine are working fine. I'm not that much of a Rails guru.

**Comment by jcatrysse** [comment]
The new versions long surpass this issue, so I closed it.
