### ISSUE TITLE
mimemagick still required

### ISSUE THREAD

**Issue by acosonic** [HugoHasenbein/redmine_more_previews#47]
```
grep -R mimemagi 

plugins/redmine_more_previews/README.md:  - fixed mimemagick dependency after license change
plugins/redmine_more_previews/Gemfile:#gem 'mimemagic', '~> 0.3.8'
plugins/redmine_more_previews/init.rb:#        - fixed dependency on mimemagick after license change
plugins/redmine_more_previews/init.rb:#        - fixed dependency on mimemagick after license change
**plugins/redmine_more_previews/lib/redmine_more_previews/patches/repository_patch.rb:require 'mimemagic'
plugins/redmine_more_previews/lib/redmine_more_previews/patches/repository_patch.rb:require 'mimemagic/overlay'
plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachment_patch.rb:require 'mimemagic'
plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachment_patch.rb:require 'mimemagic/overlay'
plugins/redmine_more_previews/lib/redmine_more_previews/converter.rb:require 'mimemagic'
plugins/redmine_more_previews/lib/redmine_more_previews/converter.rb:require 'mimemagic/overlay'**
```

crashes with following dump:
```
cannot load such file -- mimemagic (LoadError)
  /home/rmdev/.rvm/gems/ruby-2.6.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
```

**Comment by HugoHasenbein** [comment]
Dear Aleksander,

try to uncomment

plugins/redmine_more_previews/Gemfile:#gem 'mimemagic', '~> 0.3.8'
then do

bundle install

then restart redmine

There has been much ado about mimemgaic in the past. Soon I will publish a new version, which will take care of the mimnemagic issue

Best regards

Stephan

**Comment by acosonic** [comment]
Works now, also there's some warnings now:

```
/home/aco/ruby/redmine/plugins/redmine_more_previews/converters/cliff/lib/cliff.rb:264: warning: already initialized constant Cliff::UNSAFETAGS
/home/aco/ruby/redmine/plugins/redmine_more_previews/converters/cliff/lib/cliff.rb:264: warning: previous definition of UNSAFETAGS was here
/home/aco/ruby/redmine/plugins/redmine_more_previews/converters/libre/lib/libre.rb:27: warning: already initialized constant Libre::LIBRE_OFFICE_BIN
/home/aco/ruby/redmine/plugins/redmine_more_previews/converters/libre/lib/libre.rb:27: warning: previous definition of LIBRE_OFFICE_BIN was here
/home/aco/ruby/redmine/plugins/redmine_more_previews/converters/mark/lib/mark.rb:33: warning: already initialized constant Mark::PANDOC_BIN
/home/aco/ruby/redmine/plugins/redmine_more_previews/converters/mark/lib/mark.rb:33: warning: previous definition of PANDOC_BIN was here
/home/aco/ruby/redmine/plugins/redmine_more_previews/converters/mark/lib/mark.rb:34: warning: already initialized constant Mark::PANDOC_FRM
/home/aco/ruby/redmine/plugins/redmine_more_previews/converters/mark/lib/mark.rb:34: warning: previous definition of PANDOC_FRM was here

```

**Comment by vpnwe912** [comment]
It doesn't work here is the error

`/root/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- mimemagic (LoadError)
`

tell me how to solve this problem

**Comment by HugoHasenbein** [comment]
did you do?

bundle install

**Comment by vpnwe912** [comment]
Yes

> bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.

Your Gemfile lists the gem redmine_crm (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using i18n 1.8.11
Using minitest 5.15.0
Using thread_safe 0.3.6
Using tzinfo 1.2.9
Using activesupport 5.2.5
Using builder 3.2.4
Using erubi 1.10.0
Using racc 1.6.0
Using nokogiri 1.11.7 (x86_64-linux)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.16.0
Using rails-html-sanitizer 1.4.2
Using actionview 5.2.5
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 5.2.5
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.5
Using actioncable 5.2.5
Using globalid 1.0.0
Using activejob 5.2.5
Using mini_mime 1.0.3
Using mail 2.7.1
Using actionmailer 5.2.5
Using method_source 1.0.0
Using thor 1.2.1
Using railties 5.2.5
Using actionpack-xml_parser 2.0.1
Using activemodel 5.2.5
Using arel 9.0.0
Using activerecord 5.2.5
Using marcel 1.0.2
Using activestorage 5.2.5
Using public_suffix 4.0.7
Using addressable 2.8.0
Using bundler 2.3.11
Using chunky_png 1.4.0
Using css_parser 1.11.0
Using csv 3.1.9
Using htmlentities 4.3.4
Using liquid 2.6.3
Using mini_magick 4.11.0
Using mysql2 0.5.3
Using net-ldap 0.17.0
Using ruby-openid 2.9.2
Using rack-openid 1.4.2
Using sprockets 4.0.3
Using sprockets-rails 3.4.2
Using rails 5.2.5
Using rbpdf-font 1.19.1
Using rbpdf 1.20.1
Using redcarpet 3.5.1
Using rubyzip 2.3.2
Using redmine_crm 0.0.56
Using request_store 1.5.1
Using roadie 4.0.0
Using roadie-rails 2.2.0
Using rotp 6.2.0
Using rouge 3.26.1
Using rqrcode_core 1.2.0
Using rqrcode 2.1.1
Using vcard 0.3.0
Using zlib 2.1.1
Bundle complete! 45 Gemfile dependencies, 67 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

**Comment by HugoHasenbein** [comment]
which version of redmine_more_previews are you running?

**Comment by vpnwe912** [comment]
downloaded an hour ago

**Comment by HugoHasenbein** [comment]
do bundle install with redmine privileges, not as root. possibly mimemagic is installed in the wrong place (in root).
if that fails, do

gem install mimemagic

**Comment by vpnwe912** [comment]
> gem list | grep mimemagic
mimemagic (0.4.3, 0.3.10)

> /root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- mimemagic (LoadError)

**Comment by HugoHasenbein** [comment]
there must be a rails configuration error. the gem is installed, but cannot be loaded. You are sure, it is installed with the same user as the process user running redmine?

**Comment by vpnwe912** [comment]
yes, I now installed everything as root and ran it as root

**Comment by HugoHasenbein** [comment]
you may have to install

freedesktop.org.xml

look on GitHub

https://github.com/mimemagicrb/mimemagic <https://github.com/mimemagicrb/mimemagic>

there: Dependencies

**Comment by acosonic** [comment]
I have finally made working by changing Gemfile like:

#unless Gem::Specification.all_names.any?{|gem| gem =~ /mimemagic/}
gem 'mimemagic', '0.3.5', github: 'planb137/mimemagic', branch: 'master'
#end

**Comment by HugoHasenbein** [comment]
then open the console

rails c -e production

then, in the console do

Gem::Specification.all_names

mimemagic should be present

then do

require 'mimemagic'

and return me the error
