### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by higgins29200** [HugoHasenbein/redmine_more_previews#55]
Hello,

I'got a problem while installing this plugins. I have another older configuration who work well but I installed a new instance and get the following error:

Redmine version : 4.2 (from docker hub).
After `bundle install` who work without warning or error, I ran a `bundle exec rake test` and get the following issue :
```
I, [2022-05-24T21:02:51.464241 #1650]  INFO -- : Trying to copy /usr/src/redmine/plugins/redmine_more_previews/config/install/../../assets/pages/install_error.html to /usr/src/redmine/public/plugin_assets/redmine_more_previews/pages}
W, [2022-05-24T21:02:51.700607 #1650]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2022-05-24T21:02:52.264498 #1650]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2022-05-24T21:02:52.271249 #1650]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
rake aborted!
LoadError: cannot load such file -- redmine_more_previews/patches/entry_patch
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/usr/src/redmine/plugins/redmine_more_previews/lib/redmine_more_previews/patches.rb:23:in `<top (required)>'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:244:in `block (2 levels) in eager_load'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
/usr/src/redmine/config/environment.rb:16:in `<top (required)>'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
/usr/src/redmine/test/test_helper.rb:30:in `<top (required)>'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
/usr/src/redmine/test/functional/account_controller_test.rb:20:in `<top (required)>'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/test_unit/runner.rb:50:in `block in load_tests'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/test_unit/runner.rb:50:in `each'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/test_unit/runner.rb:50:in `load_tests'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/test_unit/runner.rb:39:in `run'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/test_unit/runner.rb:35:in `rake_run'
/usr/local/bundle/gems/railties-6.1.6/lib/rails/test_unit/testing.rake:16:in `block in <top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```
Thank's a lot for your help,

**Comment by higgins29200** [comment]
Sorry, I just realized I installed Redmine 5 via docker. 

I followed another issue solution (mark as solved) and it works now.
