### ISSUE TITLE
see the log

### ISSUE THREAD

**Issue by perryjun** [HugoHasenbein/redmine_more_previews#61]
C:\Bitnami\redmine-5.0.0-2\apps\redmine\htdocs>bundle exec thin start -e production -p 3001 --prefix /redmine
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/digest-3.1.0-x64-mingw32/lib/digest.rb:20: warning: already initialized constant Digest::REQUIRE_MUTEX
C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/digest.rb:6: warning: previous definition of REQUIRE_MUTEX was here
2022-07-14 14:32:24 +0800 Using rack adapter
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_issues_visibility/lib/redmine_issues_visibility/patches/role_patch.rb:8: warning: already initialized constant Role::ISSUES_VISIBILITY_OPTIONS
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/app/models/role.rb:40: warning: previous definition of ISSUES_VISIBILITY_OPTIONS was here
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_knowledgebase
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get': uninitialized constant Views (NameError)
Did you mean?  Viewing
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:244:in `block (2 levels) in eager_load'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:347:in `call'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config.ru:3:in `require'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config.ru:3:in `block in <main>'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config.ru:1:in `new'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config.ru:1:in `<main>'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/rack/adapter/loader.rb:33:in `eval'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/rack/adapter/loader.rb:33:in `load'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/rack/adapter/loader.rb:42:in `for'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/thin/controllers/controller.rb:170:in `load_adapter'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/thin/controllers/controller.rb:74:in `start'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/thin/runner.rb:203:in `run_command'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/thin/runner.rb:159:in `run!'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/bin/thin:6:in `<top (required)>'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/bin/thin:23:in `load'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/bin/thin:23:in `<main>'

**Comment by hellosnowy** [comment]
Using your latest submitted version 5.0.2，commit af4c4607affe11acf2f98f28520dcbb947faff2d


C:\Bitnami\redmine-5.0.0-2\apps\redmine\htdocs>bundle exec thin start -e production -p 3001 --prefix /redmin
2022-07-22 15:58:44 +0800 Using rack adapter
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get': uninitialized constant Views (NameError)
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:244:in `block (2 levels) in eager_load'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:347:in `call'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        from C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config.ru:3:in `require'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config.ru:3:in `block in <main>'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config.ru:1:in `new'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config.ru:1:in `<main>'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/rack/adapter/loader.rb:33:in `eval'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/rack/adapter/loader.rb:33:in `load'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/rack/adapter/loader.rb:42:in `for'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/thin/controllers/controller.rb:170:in `load_adapter'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/thin/controllers/controller.rb:74:in `start'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/thin/runner.rb:203:in `run_command'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/lib/thin/runner.rb:159:in `run!'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/thin-1.8.0-x64-mingw32/bin/thin:6:in `<top (required)>'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/bin/thin:23:in `load'
        from C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/bin/thin:23:in `<main>'

**Comment by perryjun** [comment]
what's the problem, still cann't run...
C:\Bitnami\redmine-5.0.0-2\apps\redmine\htdocs\plugins>bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs)
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/digest-3.1.0-x64-mingw32/lib/digest.rb:20: warning: already initialized constant Digest::REQUIRE_MUTEX
C:/Bitnami/redmine-5.0.0-2/ruby/lib/ruby/2.6.0/digest.rb:6: warning: previous definition of REQUIRE_MUTEX was here
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_issues_visibility/lib/redmine_issues_visibility/patches/role_patch.rb:8: warning: already initialized constant Role::ISSUES_VISIBILITY_OPTIONS
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/app/models/role.rb:40: warning: previous definition of ISSUES_VISIBILITY_OPTIONS was here
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_knowledgebase
rake aborted!
TypeError: wrong argument type Class (expected Module)
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:37:in `include'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:37:in `<class:Conversion>'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:28:in `<module:RedmineMorePreviews>'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:26:in `<top (required)>'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_more_previews/lib/redmine_more_previews.rb:30:in `require_relative'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_more_previews/lib/redmine_more_previews.rb:30:in `<top (required)>'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_more_previews/init.rb:139:in `require_relative'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/plugins/redmine_more_previews/init.rb:139:in `<top (required)>'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:31:in `load'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:31:in `run_initializer'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:108:in `each'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/lib/redmine/plugin_loader.rb:108:in `block in load'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:427:in `instance_exec'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:603:in `catch'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:199:in `block in halting'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `each'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `invoke_before'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/reloader.rb:88:in `prepare!'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/application.rb:367:in `require_environment!'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/railties-6.1.4.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
C:/Bitnami/redmine-5.0.0-2/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by HugoHasenbein** [comment]
5.0.5? I cannot reproduce the error here, therefore, I amend the code slowly

**Comment by perryjun** [comment]
> 

5.0.0 and 5.0.2 redmine，the same result.  Windows System

**Comment by HugoHasenbein** [comment]
current version is 5.0.5

**Comment by HugoHasenbein** [comment]
try version 5.0.6 now on github

**Comment by perryjun** [comment]
finnally, it is running，but i have another question, how to install libreoffice to make this plugin works
