### ISSUE TITLE
XLSX file not working

### ISSUE THREAD

**Issue by Nixan04** [HugoHasenbein/redmine_more_previews#83]
Hai, I am facing an issue when i upload "XLSX" file and when i click on the link I am not able to view the content with the preview plugin and i have one more issue related in "EML" file Please do help me  in it.

In error log i am getting "cannot stat './230616085555_bd2394073a8458424521fb9f1eaf82bf.html'
App 1207 output: : No such file or directory"

**Comment by HugoHasenbein** [comment]
go ahead, what's the issue?

Am 2023-06-16 11:01, schrieb Nixan04:

**Comment by Nixan04** [comment]
Hi , I am not able to view the proper content of "EML" using preview plugin and i am getting text like below


No such file or directory @ rb_sysopen - jenkins.txt
/var/lib/gems/2.7.0/gems/marcel-1.0.2/lib/marcel/mime_type.rb:64:in `initialize'
/var/lib/gems/2.7.0/gems/marcel-1.0.2/lib/marcel/mime_type.rb:64:in `open'
/var/lib/gems/2.7.0/gems/marcel-1.0.2/lib/marcel/mime_type.rb:64:in `open'
/var/lib/gems/2.7.0/gems/marcel-1.0.2/lib/marcel/mime_type.rb:64:in `with_io'
/var/lib/gems/2.7.0/gems/marcel-1.0.2/lib/marcel/mime_type.rb:30:in `for_data'
/var/lib/gems/2.7.0/gems/marcel-1.0.2/lib/marcel/mime_type.rb:17:in `for'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachment_patch.rb:102:in `asset_link'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/core_ext/object/try.rb:15:in `public_send'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/core_ext/object/try.rb:15:in `try'
(erb):5:in `block in list'
(erb):2:in `each'
(erb):2:in `list'
/usr/lib/ruby/2.7.0/erb.rb:905:in `eval'
/usr/lib/ruby/2.7.0/erb.rb:905:in `result'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/converters/cliff/lib/cliff.rb:378:in `list'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/converters/cliff/lib/cliff.rb:93:in `eml'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/converters/cliff/lib/cliff.rb:46:in `convert'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:193:in `block in transient_preview'
/usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:186:in `transient_preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:208:in `cached_preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:172:in `block in preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:137:in `synchronize'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:137:in `sync'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:172:in `preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/converter.rb:265:in `convert'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachment_patch.rb:37:in `more_preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:93:in `send_more_preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:61:in `block (2 levels) in more_preview'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:60:in `more_preview'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/abstract_controller/base.rb:228:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/var/www/pms.ivldsp.com/lib/redmine/sudo_mode.rb:61:in `sudo_mode'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:137:in `run_callbacks'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/abstract_controller/callbacks.rb:41:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/rescue.rb:22:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `block in instrument'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `instrument'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
/var/lib/gems/2.7.0/gems/activerecord-6.1.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/abstract_controller/base.rb:165:in `process'
/var/lib/gems/2.7.0/gems/actionview-6.1.7/lib/action_view/rendering.rb:39:in `process'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal.rb:190:in `dispatch'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal.rb:254:in `dispatch'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:32:in `each'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:32:in `serve'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/routing/route_set.rb:842:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/tempfile_reaper.rb:15:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/etag.rb:27:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/conditional_get.rb:27:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/head.rb:12:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/session/abstract/id.rb:266:in `context'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/session/abstract/id.rb:260:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/cookies.rb:689:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:98:in `run_callbacks'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/rack/logger.rb:37:in `call_app'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/rack/logger.rb:26:in `block in call'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:37:in `tagged'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `tagged'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/rack/logger.rb:26:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/var/lib/gems/2.7.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/method_override.rb:24:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/runtime.rb:22:in `call'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/static.rb:24:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/sendfile.rb:110:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/content_length.rb:17:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:539:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by HugoHasenbein** [comment]
Dear Nixan,
it seems, marcel, a gem that comes with redmine, does have a 
configuration or installation issue.
Best regards
Stephan

Am 2023-06-16 12:32, schrieb Nixan04:

**Comment by Nixan04** [comment]
Hi,
   Do you any steps or methods to solve this issue. Please let me know it.

**Comment by HugoHasenbein** [comment]
try to enable cache mode in the plugin's configuration menu. Then, in the root directory in files/ try to find the created preview file.

**Comment by Nixan04** [comment]
XLSX file preview is supported can please check it and give a update?

**Comment by Nixan04** [comment]
I have found the file . then how to enable the cache mode ?please help with this?

**Comment by HugoHasenbein** [comment]
the cache mode is enabled by the plugin configuration page under Administration -> Plugins -> Redmine More Previews.

If cache mode does not work, could you send the offending xlsx-file? (only if it show non secret data)

**Comment by Nixan04** [comment]
I am not able to find in the location .

**Comment by HugoHasenbein** [comment]
Administration -> Plugins -> Redmine More Previews

**Comment by Nixan04** [comment]
okay.  this working only for pdf and image files only and not for any other format. Is this working for you . please give a hand help for me.

**Comment by HugoHasenbein** [comment]
Dear Nixan,

I'm trying to help, but you provide very sparse information. I would need the screen shot of the configuration page of the plugin. Please set the plugin to cache mode and try to find the converted file in the /files directory of redmines root directory. Further, send me a log file output.

Best regards

Stephan

**Comment by Nixan04** [comment]
Below is the error log after import  xlsx-file to the redmine:

 --headless --convert-to html --outdir '/tmp/d20230621-1229-1y161uk' -env:UserInstallation=file:///tmp/d20230621-1229-d8b884/user_installation '/var/www/pms.ivldsp.com/files/2023/06/230621041518_eae1ee3574bbd7d858a1e62b3ecbe2ec.xlsx'; mv './230621041518_eae1ee3574bbd7d858a1e62b3ecbe2ec.html' '/tmp/d20230621-1229-1y161uk/index.html'
E, [2023-06-21T09:13:16.910064 #1229] ERROR -- : [bc391760-5ad7-486d-8e3f-1c239a2f53be] An error occured while generating preview for /var/www/pms.ivldsp.com/files/2023/06/230621041518_eae1ee3574bbd7d858a1e62b3ecbe2ec.xlsx
E, [2023-06-21T09:13:16.910115 #1229] ERROR -- : [bc391760-5ad7-486d-8e3f-1c239a2f53be] Exception was: RedmineMorePreviews::Exceptions::ConverterShellError
E, [2023-06-21T09:13:16.910324 #1229] ERROR -- : [bc391760-5ad7-486d-8e3f-1c239a2f53be] /var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:340:in `command'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/converters/libre/lib/libre.rb:41:in `block in convert'
/usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/converters/libre/lib/libre.rb:39:in `convert'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:193:in `block in transient_preview'
/usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:186:in `transient_preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:208:in `cached_preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:172:in `block in preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:137:in `synchronize'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:137:in `sync'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/conversion.rb:172:in `preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/converter.rb:265:in `convert'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachment_patch.rb:37:in `more_preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:93:in `send_more_preview'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:61:in `block (2 levels) in more_preview'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
/var/www/pms.ivldsp.com/plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:60:in `more_preview'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/abstract_controller/base.rb:228:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/var/www/pms.ivldsp.com/lib/redmine/sudo_mode.rb:61:in `sudo_mode'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:137:in `run_callbacks'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/abstract_controller/callbacks.rb:41:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/rescue.rb:22:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `block in instrument'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `instrument'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
/var/lib/gems/2.7.0/gems/activerecord-6.1.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/abstract_controller/base.rb:165:in `process'
/var/lib/gems/2.7.0/gems/actionview-6.1.7/lib/action_view/rendering.rb:39:in `process'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal.rb:190:in `dispatch'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_controller/metal.rb:254:in `dispatch'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:32:in `each'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/journey/router.rb:32:in `serve'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/routing/route_set.rb:842:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/tempfile_reaper.rb:15:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/etag.rb:27:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/conditional_get.rb:27:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/head.rb:12:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/session/abstract/id.rb:266:in `context'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/session/abstract/id.rb:260:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/cookies.rb:689:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:98:in `run_callbacks'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/rack/logger.rb:37:in `call_app'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/rack/logger.rb:26:in `block in call'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:37:in `tagged'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `tagged'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/rack/logger.rb:26:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/var/lib/gems/2.7.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/method_override.rb:24:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/runtime.rb:22:in `call'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/static.rb:24:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/sendfile.rb:110:in `call'
/var/lib/gems/2.7.0/gems/rack-2.2.5/lib/rack/content_length.rb:17:in `call'
/var/lib/gems/2.7.0/gems/actionpack-6.1.7/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:539:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
I, [2023-06-21T09:13:16.911194 #1229]  INFO -- : [bc391760-5ad7-486d-8e3f-1c239a2f53be]   Rendered text template (Duration: 0.0ms | Allocations: 1)
I, [2023-06-21T09:13:16.911330 #1229]  INFO -- : [bc391760-5ad7-486d-8e3f-1c239a2f53be] Sent data index.html (0.8ms)
I, [2023-06-21T09:13:16.914400 #1229]  INFO -- : [bc391760-5ad7-486d-8e3f-1c239a2f53be] Completed 200 OK in 25ms (Views: 0.4ms | ActiveRecord: 4.7ms | Allocations: 6933)





![Untitled](https://github.com/HugoHasenbein/redmine_more_previews/assets/85859071/95fd087e-56e6-4cb3-8996-9513da40ed23)

**Comment by jcatrysse** [comment]
This plugin requires LibreOffice to be installed on your system. LibreOffice must be reachable with "soffice" to the user, the Redmine service is executed by. Please also verify `/tmp` is writable by your `www` or other Redmine user.

This is also described in [the readme](https://github.com/HugoHasenbein/redmine_more_previews/blob/main/README.md)

**Comment by Nixan04** [comment]
[screencapture-43-205-92-4-attachments-310-2023-06-21-15_02_00.pdf](https://github.com/HugoHasenbein/redmine_more_previews/files/11815961/screencapture-43-205-92-4-attachments-310-2023-06-21-15_02_00.pdf)




error log now i am facing:

I, [2023-06-21T09:33:15.716809 #16332]  INFO -- : [4111bc91-a3fd-4cee-8ac0-613b8aefc055] Started GET "/attachments/310" for 103.121.27.66 at 2023-06-21 09:33:15 +0000
I, [2023-06-21T09:33:15.717587 #16332]  INFO -- : [4111bc91-a3fd-4cee-8ac0-613b8aefc055] Processing by AttachmentsController#show as HTML
I, [2023-06-21T09:33:15.717646 #16332]  INFO -- : [4111bc91-a3fd-4cee-8ac0-613b8aefc055]   Parameters: {"id"=>"310"}
I, [2023-06-21T09:33:15.744367 #16332]  INFO -- : [4111bc91-a3fd-4cee-8ac0-613b8aefc055]   Current user: admin (id=1)
I, [2023-06-21T09:33:15.844602 #16332]  INFO -- : [4111bc91-a3fd-4cee-8ac0-613b8aefc055]   Rendered plugins/redmine_more_previews/app/views/attachments/more_preview.html.erb within layouts/base (Duration: 53.6ms | Allocations: 8301)
I, [2023-06-21T09:33:15.858786 #16332]  INFO -- : [4111bc91-a3fd-4cee-8ac0-613b8aefc055]   Rendered inline template (Duration: 0.4ms | Allocations: 161)
I, [2023-06-21T09:33:15.865057 #16332]  INFO -- : [4111bc91-a3fd-4cee-8ac0-613b8aefc055]   Rendered inline template (Duration: 4.0ms | Allocations: 159)
I, [2023-06-21T09:33:15.865717 #16332]  INFO -- : [4111bc91-a3fd-4cee-8ac0-613b8aefc055]   Rendered inline template (Duration: 0.4ms | Allocations: 159)
I, [2023-06-21T09:33:15.994962 #16332]  INFO -- : [4111bc91-a3fd-4cee-8ac0-613b8aefc055]   Rendered layout layouts/base.html.erb (Duration: 204.0ms | Allocations: 28119)
I, [2023-06-21T09:33:15.999869 #16332]  INFO -- : [4111bc91-a3fd-4cee-8ac0-613b8aefc055] Completed 200 OK in 280ms (Views: 175.8ms | ActiveRecord: 77.4ms | Allocations: 32787)
I, [2023-06-21T09:33:16.147039 #16332]  INFO -- : [e453f417-0643-4a04-afc7-2162d2fa7ffb] Started GET "/attachments/more_preview/310/index.html" for 103.121.27.66 at 2023-06-21 09:33:16 +0000
I, [2023-06-21T09:33:16.148476 #16332]  INFO -- : [e453f417-0643-4a04-afc7-2162d2fa7ffb] Processing by AttachmentsController#more_preview as HTML
I, [2023-06-21T09:33:16.148929 #16332]  INFO -- : [e453f417-0643-4a04-afc7-2162d2fa7ffb]   Parameters: {"id"=>"310"}
I, [2023-06-21T09:33:16.170382 #16332]  INFO -- : [e453f417-0643-4a04-afc7-2162d2fa7ffb]   Current user: admin (id=1)
I, [2023-06-21T09:33:16.202981 #16332]  INFO -- : [e453f417-0643-4a04-afc7-2162d2fa7ffb]   Rendered text template (Duration: 0.0ms | Allocations: 1)
I, [2023-06-21T09:33:16.206210 #16332]  INFO -- : [e453f417-0643-4a04-afc7-2162d2fa7ffb] Sent data index.html (4.6ms)
I, [2023-06-21T09:33:16.213189 #16332]  INFO -- : [e453f417-0643-4a04-afc7-2162d2fa7ffb] Completed 200 OK in 64ms (Views: 2.1ms | ActiveRecord: 19.3ms | Allocations: 6720)
I, [2023-06-21T09:33:16.295220 #16332]  INFO -- : [8b54e5ac-7a87-4658-b8b6-8fcb29586865] Started GET "/attachments/more_preview/310/emoji4.png" for 103.121.27.66 at 2023-06-21 09:33:16 +0000
I, [2023-06-21T09:33:16.296089 #16332]  INFO -- : [8b54e5ac-7a87-4658-b8b6-8fcb29586865] Processing by AttachmentsController#more_asset as PNG
I, [2023-06-21T09:33:16.296155 #16332]  INFO -- : [8b54e5ac-7a87-4658-b8b6-8fcb29586865]   Parameters: {"id"=>"310", "asset"=>"emoji4", "assetformat"=>"png"}
I, [2023-06-21T09:33:16.299931 #16332]  INFO -- : [8b54e5ac-7a87-4658-b8b6-8fcb29586865]   Current user: admin (id=1)
I, [2023-06-21T09:33:16.309629 #16332]  INFO -- : [8b54e5ac-7a87-4658-b8b6-8fcb29586865] Completed 304 Not Modified in 13ms (ActiveRecord: 2.5ms | Allocations: 8576)

**Comment by jcatrysse** [comment]
You should disable the `debug` mode and `update` your page again. Make sure to click on `update`, otherwise you will just retrieve the cached version.

![afbeelding](https://github.com/HugoHasenbein/redmine_more_previews/assets/23419642/869ac11f-c4ff-4661-abc3-13157b184775)

**Comment by Nixan04** [comment]
when i am uploading "EML" file iam get following page. please help me with this ?


[screencapture-43-205-92-4-attachments-321-2023-06-21-15_29_10.pdf](https://github.com/HugoHasenbein/redmine_more_previews/files/11816234/screencapture-43-205-92-4-attachments-321-2023-06-21-15_29_10.pdf)

**Comment by jcatrysse** [comment]
I hate to say this, but you should really try to do an effort communicating:
1. What was the result of the last step?
2. What is the expected behavior?
3. Please provide an example file.
4. What did you already try?
5. Did you try `reloading` and `safe reload`?

Furthermore, please try to resolve basic issues and `rtfrm` (you can Google that last one ;-) )

`rb_sysopen` indicates the files are missing or not accessible, so it could be a permission issue.

**Comment by Nixan04** [comment]
The issue for the xlsx was solved as you have mentioned .thank you for your support . 

when i am uploading "EML" file iam get following page. please help me with this ?

[screencapture-43-205-92-4-attachments-321-2023-06-21-15_29_10.pdf](https://github.com/HugoHasenbein/redmine_more_previews/files/11816234/screencapture-43-205-92-4-attachments-321-2023-06-21-15_29_10.pdf)

**Comment by HugoHasenbein** [comment]
can the eml-file be shared, so I can have a closer look on what happens?

**Comment by HugoHasenbein** [comment]
Your screenshot shows, that there is a header X-MS-TNEF-CORRELATOR.

Is the email a Microsoft-Outlook-File, which has been converted to an .eml-file by a tool such as msgconvert or the like?
