### ISSUE TITLE
Installation causes fatal error in existing plugin additional_tags

### ISSUE THREAD

**Issue by batrachian** [HugoHasenbein/redmine_more_previews#91]
Installing `redmine_more_previews` alongside `alphanodes/additional_tags` results in a fatal error.  Hoping someone might be able to provide clues as to what is causing the fault so it can be resolved.

An issue has been created in the additional_tags project [here](https://github.com/alphanodes/additional_tags/issues/56)

```
F, [2023-10-08T03:05:25.360235 #9893] FATAL -- : [47a97f8d-94d4-4b6c-939e-7943f247591e]   
[47a97f8d-94d4-4b6c-939e-7943f247591e] ActionView::Template::Error (Array::ArrayRowIsNotAHash):
[47a97f8d-94d4-4b6c-939e-7943f247591e]     1: - if AdditionalTags.setting?(:active_issue_tags) && \
[47a97f8d-94d4-4b6c-939e-7943f247591e]     2:      User.current.allowed_to?(:view_issue_tags, @project, global: true) && \
[47a97f8d-94d4-4b6c-939e-7943f247591e]     3:      defined?(sidebar_tags) && \
[47a97f8d-94d4-4b6c-939e-7943f247591e]     4:      sidebar_tags.present?
[47a97f8d-94d4-4b6c-939e-7943f247591e]     5: 
[47a97f8d-94d4-4b6c-939e-7943f247591e]     6:   .sidebar-tags
[47a97f8d-94d4-4b6c-939e-7943f247591e]     7:     h3 = l :field_tags
[47a97f8d-94d4-4b6c-939e-7943f247591e]   
[47a97f8d-94d4-4b6c-939e-7943f247591e] plugins/additional_tags/lib/additional_tags/tags.rb:149:in `table_columns'
[47a97f8d-94d4-4b6c-939e-7943f247591e] plugins/additional_tags/lib/additional_tags/tags.rb:35:in `available_tags'
[47a97f8d-94d4-4b6c-939e-7943f247591e] plugins/additional_tags/lib/additional_tags/patches/issue_patch.rb:49:in `available_tags'
[47a97f8d-94d4-4b6c-939e-7943f247591e] plugins/additional_tags/app/helpers/additional_tags_issues_helper.rb:49:in `sidebar_tags'
[47a97f8d-94d4-4b6c-939e-7943f247591e] plugins/additional_tags/app/views/issues/_tags_sidebar.html.slim:4
[47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook/view_listener.rb:61:in `block (2 levels) in render_on'
[47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook/view_listener.rb:59:in `map'
[47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook/view_listener.rb:59:in `block in render_on'
[47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
[47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook.rb:66:in `each'
[47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook.rb:66:in `block in call_hook'
[47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook.rb:63:in `call_hook'
[47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook.rb:101:in `call_hook'
[47a97f8d-94d4-4b6c-939e-7943f247591e] app/views/issues/_sidebar.html.erb:2
[47a97f8d-94d4-4b6c-939e-7943f247591e] app/views/issues/show.html.erb:137
[47a97f8d-94d4-4b6c-939e-7943f247591e] app/views/issues/show.html.erb:136
[47a97f8d-94d4-4b6c-939e-7943f247591e] app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
[47a97f8d-94d4-4b6c-939e-7943f247591e] app/controllers/issues_controller.rb:110:in `show'
[47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by HugoHasenbein** [comment]
Dear Batrachian,

this is a good one.

the plugin 'additional_tags' requires the 'additionals' plugin.

Apparently, the author of the 'additionals' plugin has patched the Array 
core class in ruby, namely in

additionals/lib/additionals.rb, lines 200 ff:

class Array
   # alias for join with ', ' as seperator
   def to_list
     join ', '
   end
end

Thus, the author defines the method to_list to be an "alias" as he 
writes in his comment

The RedmineMorePreviews plugin requires the "hash_base" gem, which I 
have written. Hash base adds a plurality of Array manipulating methods, 
inter alia "to_list". The "to_list" method provides a sorted array list 
from an array of hashes. This is similar to the methods the CSV gem 
does, but in another fashion. I use the has_base gem heavily in a 
plurality of plugins.

This, there is indeed a collision.

Solution: since in additionals the "alias" to_list is used only in a 
very few instances and the to_list method can be replaced by "join(", 
"), I propose that additionals amended.

Best regards

Stephan

Am 2023-10-08 05:03, schrieb batrachian:

> Installing redmine_more_previews alongside alphanodes/additional_tags 
> results in a fatal error. Hoping someone might be able to provide clues 
> as to what is causing the fault so it can be resolved.
> 
> An issue has been created in the additional_tags project here [1]
> 
> F, [2023-10-08T03:05:25.360235 #9893] FATAL -- : 
> [47a97f8d-94d4-4b6c-939e-7943f247591e]
> [47a97f8d-94d4-4b6c-939e-7943f247591e] ActionView::Template::Error 
> (Array::ArrayRowIsNotAHash):
> [47a97f8d-94d4-4b6c-939e-7943f247591e]     1: - if 
> AdditionalTags.setting?(:active_issue_tags) && \
> [47a97f8d-94d4-4b6c-939e-7943f247591e]     2:      
> User.current.allowed_to?(:view_issue_tags, @project, global: true) && \
> [47a97f8d-94d4-4b6c-939e-7943f247591e]     3:      
> defined?(sidebar_tags) && \
> [47a97f8d-94d4-4b6c-939e-7943f247591e]     4:      
> sidebar_tags.present?
> [47a97f8d-94d4-4b6c-939e-7943f247591e]     5:
> [47a97f8d-94d4-4b6c-939e-7943f247591e]     6:   .sidebar-tags
> [47a97f8d-94d4-4b6c-939e-7943f247591e]     7:     h3 = l :field_tags
> [47a97f8d-94d4-4b6c-939e-7943f247591e]
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> plugins/additional_tags/lib/additional_tags/tags.rb:149:in 
> `table_columns'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> plugins/additional_tags/lib/additional_tags/tags.rb:35:in 
> `available_tags'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> plugins/additional_tags/lib/additional_tags/patches/issue_patch.rb:49:in 
> `available_tags'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> plugins/additional_tags/app/helpers/additional_tags_issues_helper.rb:49:in 
> `sidebar_tags'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> plugins/additional_tags/app/views/issues/_tags_sidebar.html.slim:4
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> lib/redmine/hook/view_listener.rb:61:in `block (2 levels) in render_on'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> lib/redmine/hook/view_listener.rb:59:in `map'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> lib/redmine/hook/view_listener.rb:59:in `block in render_on'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook.rb:66:in `block 
> (2 levels) in call_hook'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook.rb:66:in `each'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook.rb:66:in `block 
> in call_hook'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook.rb:63:in 
> `call_hook'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/hook.rb:101:in 
> `call_hook'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> app/views/issues/_sidebar.html.erb:2
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> app/views/issues/show.html.erb:137
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> app/views/issues/show.html.erb:136
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] 
> app/controllers/issues_controller.rb:110:in `show'
> [47a97f8d-94d4-4b6c-939e-7943f247591e] lib/redmine/sudo_mode.rb:61:in 
> `sudo_mode'
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you are subscribed to this 
> thread.Message ID: 
> ***@***.***>



Links:
------
[1] https://github.com/alphanodes/additional_tags/issues/56
[2] https://github.com/HugoHasenbein/redmine_more_previews/issues/91
[3]

**Comment by batrachian** [comment]
Hi Stephan,

Thank you very much for you quick response and detailed analysis.

I can confirm that making your suggested changes to the additionals/additional_tags plugins eliminates the conflict.

I will advise alphanodes of your proposed solution.


Best regards,

Wayne
