### ISSUE TITLE
Redmine 5.1.1 not launching after plugin install 

### ISSUE THREAD

**Issue by nekrasovdmitriy** [HugoHasenbein/redmine_more_previews#97]
![Снимок экрана 2024-04-20 в 22 46 27](https://github.com/HugoHasenbein/redmine_more_previews/assets/18664106/3ee1b53e-a198-4a11-8717-bd8590e3611c)
Redmine shows internal error after installing plugin. Libreoffice is installed (via apt) and additional gems also.

**Comment by HugoHasenbein** [comment]
Dear Dmitry,

can you share the error in the log file?

**Comment by greedwind** [comment]
root@xxxxx:/mnt/d/Projects/Redmine/redmine-5.1.3# bundle exec rake redmine:plugins:migrate RAILS_ENV=development
rake aborted!
TypeError: no implicit conversion of Array into String (TypeError)

ActiveSupport::Dependencies.explicitly_unloadable_constants += ['RedmineMorePreviews']
                                                               ^^^^^^^^^^^^^^^^^^^^^^^
/mnt/d/Projects/Redmine/redmine-5.1.3/plugins/redmine_more_previews/init.rb:198:in `+'
/mnt/d/Projects/Redmine/redmine-5.1.3/plugins/redmine_more_previews/init.rb:198:in `<top (required)>'
/mnt/d/Projects/Redmine/redmine-5.1.3/lib/redmine/plugin_loader.rb:31:in `load'
/mnt/d/Projects/Redmine/redmine-5.1.3/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/mnt/d/Projects/Redmine/redmine-5.1.3/lib/redmine/plugin_loader.rb:108:in `each'
/mnt/d/Projects/Redmine/redmine-5.1.3/lib/redmine/plugin_loader.rb:108:in `block in load'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:427:in `instance_exec'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:603:in `catch'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in `each'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in `invoke_before'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:105:in `run_callbacks'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/reloader.rb:88:in `prepare!'
/usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `run'
/usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/application.rb:391:in `initialize!'
/mnt/d/Projects/Redmine/redmine-5.1.3/config/environment.rb:16:in `<top (required)>'
<internal:/usr/local/rvm/rubies/ruby-3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/rvm/rubies/ruby-3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/usr/local/rvm/gems/ruby-3.2.4/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
/usr/local/rvm/gems/ruby-3.2.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
/usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/application.rb:367:in `require_environment!'
/usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-3.2.4/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.2.4/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.2.4/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by HugoHasenbein** [comment]
Interesting. It seems, redline has altered its initialization concept. 
I'll have a look into that.

Am 2024-08-02 05:41, schrieb greedwind:

> ***@***.***:/mnt/d/Projects/Redmine/redmine-5.1.3# bundle exec rake 
> redmine:plugins:migrate RAILS_ENV=development
> rake aborted!
> TypeError: no implicit conversion of Array into String (TypeError)
> 
> ActiveSupport::Dependencies.explicitly_unloadable_constants += 
> ['RedmineMorePreviews']
> ^^^^^^^^^^^^^^^^^^^^^^^
> /mnt/d/Projects/Redmine/redmine-5.1.3/plugins/redmine_more_previews/init.rb:198:in 
> +' 
> /mnt/d/Projects/Redmine/redmine-5.1.3/plugins/redmine_more_previews/init.rb:198:in 
> <top (required)>'
> /mnt/d/Projects/Redmine/redmine-5.1.3/lib/redmine/plugin_loader.rb:31:in 
> load' 
> /mnt/d/Projects/Redmine/redmine-5.1.3/lib/redmine/plugin_loader.rb:31:in 
> run_initializer'
> /mnt/d/Projects/Redmine/redmine-5.1.3/lib/redmine/plugin_loader.rb:108:in 
> each' 
> /mnt/d/Projects/Redmine/redmine-5.1.3/lib/redmine/plugin_loader.rb:108:in 
> block in load'
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:427:in 
> instance_exec' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:427:in 
> block in make_lambda'
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:198:in 
> block (2 levels) in halting' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:604:in 
> block (2 levels) in default_terminator'
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:603:in 
> catch' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:603:in 
> block in default_terminator'
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:199:in 
> block in halting' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in 
> block in invoke_before'
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in 
> each' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:512:in 
> invoke_before'
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:105:in 
> run_callbacks' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/reloader.rb:88:in 
> prepare!'
> /usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/application/finisher.rb:124:in 
> block in <module:Finisher>' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in 
> instance_exec'
> /usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in 
> run' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/initializable.rb:61:in 
> block in run_initializers'
> /usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/initializable.rb:60:in 
> run_initializers' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/application.rb:391:in 
> initialize!'
> /mnt/d/Projects/Redmine/redmine-5.1.3/config/environment.rb:16:in <top 
> (required)>' 
> <internal:/usr/local/rvm/rubies/ruby-3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in 
> require'
> internal:/usr/local/rvm/rubies/ruby-3.2.4/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb:37:in 
> require' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in 
> require'
> /usr/local/rvm/gems/ruby-3.2.4/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 
> require' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in 
> block in require'
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in 
> load_dependency' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in 
> require'
> /usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/application.rb:367:in 
> require_environment!' 
> /usr/local/rvm/gems/ruby-3.2.4/gems/railties-6.1.7.8/lib/rails/application.rb:533:in 
> block in run_tasks_blocks'
> /usr/local/rvm/gems/ruby-3.2.4/gems/rake-13.2.1/exe/rake:27:in <top 
> (required)>' 
> /usr/local/rvm/gems/ruby-3.2.4/bin/ruby_executable_hooks:22:in eval'
> /usr/local/rvm/gems/ruby-3.2.4/bin/ruby_executable_hooks:22:in ` '
> Tasks: TOP => redmine:plugins:migrate => environment
> (See full trace by running task with --trace)
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you commented.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/HugoHasenbein/redmine_more_previews/issues/97#issuecomment-2264459039
[2]
